### ISSUE TITLE
Improve pipeline speed by stopping ranch prematurely.

### ISSUE THREAD

**Issue by guzmanfj** [strubelab/multiprot#11]
It would be good to stop ranch when the number of required models has been produced, instead of waiting until it builds the minimum of 10 models, as this will greatly increase the speed of the pipeline. Arnaud suggested (forgive the inaccuracy) to run it in a thread and check the status of the output folder periodically with a loop, and then stop the process when the required number of models are written. I don't know how to do that, but I'll do some research. I'm open to suggestions/information that might help.

**Comment by guzmanfj** [comment]
@graik does Biskit have a tool in the executor class or somewhere else that allows you to stop a process prematurely? So far the only idea that I have (with help from Arnaud) to achieve this is to override the `communicate` method in executor:
```
    def communicate( self, cmd, inp, bufsize=-1, executable=None,
                     stdin=None, stdout=None, stderr=None,
                     shell=0, env=None, cwd=None ):
        """
        Start and communicate with the new process. Called by execute().
        See subprocess.Popen() for a detailed description of the parameters!
        This method should work for pretty much any purpose but may fail for
        very long pipes (more than 100000 lines).
        
        :param inp: (for pipes) input sequence
        :type  inp: str
        :param cmd: command
        :type  cmd: str
        :param bufsize: see subprocess.Popen() (default: -1)
        :type  bufsize: int
        :param executable: see subprocess.Popen() (default: None)
        :type  executable: str
        :param stdin: subprocess.PIPE or file handle or None (default: None)
        :type  stdin: int|file|None
        :param stdout: subprocess.PIPE or file handle or None (default: None)
        :type  stdout: int|file|None
        :param stderr: subprocess.PIPE or file handle or None (default: None)
        :type  stderr: int|file|None
        :param shell: wrap process in shell; see subprocess.Popen()
                      (default: 0, use exe_*.dat configuration) 
        :type  shell: 1|0
        :param env: environment variables (default: None, use exe_*.dat config)
        :type  env: {str:str}
        :param cwd: working directory (default: None, means self.cwd)
        :type  cwd: str
        
        :return: output and error output
        :rtype: str, str
        
        :raise RunError: if OSError occurs during Popen or Popen.communicate
        """
        try:
            p = subprocess.Popen( cmd.split(),
                                  bufsize=bufsize, executable=executable,
                                  stdin=stdin, stdout=stdout, stderr=stderr,
                                  shell=shell or self.exe.shell,
                                  env=env or self.environment(),
                                  ## python 3.x: enforce textmode on all pipes:
                                  universal_newlines=True, 
                                  cwd=cwd or self.cwd )

            self.pid = p.pid

            output, error = p.communicate( inp )
        
            #convert byte string to actual string for Python 3.x compatibility
##            if output is not None: output = output.decode(sys.stdout.encoding)
##            if error is not None:  error  = error.decode(sys.stderr.encoding) 
            
            self.returncode = p.returncode

        except OSError as e:
            raise RunError("Couldn't run or communicate with external program: %r"\
                  % e.strerror)

        return output, error
```
So in the new method I would remove the call to `p.communicate()` and instead set up a timer to periodically check the output folder until the required number of models are produced, and then kill the process. How does that sound?

**Comment by graik** [comment]
I think the docker.py module is already doing something in this direction but is probably not using executor (was coded before). But you can check there for the thread handling. Especially the thread locking mechanism around any code that could run into a deadlock.

Technically, I agree. You could do this with the high level subprocess methods. You would have to either use the timeout parameter on the communicate function and set a fairly short timeout, or switch from communicate to subprocess.Popen which is non blocking by default.

**Comment by javierguzm** [comment]
Solved. See commit [d08e521](https://github.com/strubelab/multiprot/commit/d08e521cd243b975fb4beb4a65b4a68dde0dd132)

**Comment by guzmanfj** [comment]
Solved. See commit [970c950](https://github.com/strubelab/multiprot/commit/970c950240d7cb126a5ed897fa3a746d6252eaa4)
