### ISSUE TITLE
AttributeError: module 'multiprot' has no attribute 'parsing'

### ISSUE THREAD

**Issue by graik** [strubelab/multiprot#4]
`tests_multiprot.py` methods raise this error in the `bugfix-issue02` branch. Example:

```
git checkout bugfix-issue02
```

```py
  File "/Volumes/data/raik/py/multiprot/multiprot/tests_multiprot.py", line 89, in test_example5
    args = mp.parsing(self.argstring5.split())
AttributeError: module 'multiprot' has no attribute 'parsing'
```
Same error pops up for all the other test_* methods.

I think this happens because I renamed the multiprot module when addressing issue #2

**Comment by graik** [comment]
addressed in latest commit to bugfix-issue02 branch

**Comment by guzmanfj** [comment]
Now none of the modules nor the script are called multiprot, so that should avoid any confusion while importing... right?
