### ISSUE TITLE
circular import between multiprot_script.py and builder.py

### ISSUE THREAD

**Issue by graik** [strubelab/multiprot#8]
This pops up when I run the overall test suite but also if I run the multiprot_script.py (renamed from multiprot.py) module.

### Reproduce error:
```sh
cd multiprot
source venv/bin/activate
python multiprot/testing.py -v 2
```
Gives:
```
collecting  'multiprot'
ERROR:root:Import failure in builder: AttributeError("module 'multiprot' has no attribute 'builder'",)
```

A more detailed look gave me the following backtrace::
```
python
>>> import multiprot.builder as builder
Traceback (most recent call last):
  Python Shell, prompt 1, line 1
  File "/data/raik/py/multiprot/multiprot/builder.py", line 99, in <module>
    import multiprot.multiprot_script as mp
  File "/data/raik/py/multiprot/multiprot/multiprot_script.py", line 11, in <module>
    import multiprot.builder as builder
builtins.AttributeError: module 'multiprot' has no attribute 'builder'
```

### Problem/Diagnosis:

It looks like builder tries to import multiprot_script as a module while multiprot_script tries to import the builder module for testing which then fails because builder is not finished loading yet. 

Could be that this was hidden before I changed all the imports to absolute imports.

### Solution:

A quick fix would be to put the builder import into the __main__ section. However, this error points to a organizational issue. A module should usually not import anything from an end-user script. So there needs to be a better separation between the application script and the multiprot API / python package.

**Comment by guzmanfj** [comment]
I moved one function from `multiprot_script` (now `parseChains.py)` to `builder.py` so it doesn't have to import `parseChains.py` for that function. However, the test cases for `builder.py` still use some functions from `parseChains.py`. I did not run into any errors while running the tests, but do you think this could become an issue?

**Comment by graik** [comment]
It's better if there is no need to import from the script at all, not even for testing. It's an interesting case though. So you are basically testing the script functions in the builder module (which then of course also tests the builder itself). It would be cleaner to make a separate test_parseChains.py for testing the script and then only use direct builder calls (without argument parsing) in the builder test routines.

**Comment by guzmanfj** [comment]
Well I'm not specifically testing the `parseChains.py` functions in `builder.py`, rather the `builder.py` tests need the input from the first module, which includes some `Chain` class objects, so that's why I'm calling the functions. Is there some way to give the tests the input that they need without calling the functions from the first module?

**Comment by guzmanfj** [comment]
But I guess you're right, those tests aren't specifically for the `builder.py` functions either, but for the result of the entire pipeline. So maybe I should move those into another file like `tests_multipr.py` or something like that

**Comment by guzmanfj** [comment]
So far the errors have not appeared again... will keep my eyes open
