### ISSUE TITLE
examples_wrapper imports non-existing ranchv3 module

### ISSUE THREAD

**Issue by graik** [strubelab/multiprot#9]
This occurs when running the complete test suite (which is importing all the modules to look for test cases):

```
python multiprot/testing.py -v 2
collecting  'multiprot'
...
ERROR:root:Import failure in examples_wrapper: ImportError("No module named 'ranchv3'",)
```

**Comment by guzmanfj** [comment]
This file shouldn't be run by the testing script. I moved it into the examples/ directory.
